### ISSUE TITLE
A merged demo

### ISSUE THREAD

**Issue by grayskripko** [benjamin-meyer-ak/temp_loggers_example#1]
Hello. My name is Sergey. I just found the upwork gig you created.
Currently I'm in the process of restoring an access to my Upwork account (because of my nationality) but R-tidyverse jobs is my biggest interest and trigger so I decided to get in touch with you with this strange method.
I was on both sided, freelancer and a client, so I'm not a big fan of long discussions and prefer demos as something valueble to start communication.
This is a fast and dirty merged dataframe you wanted. I did it in 10 minutes. 
If interested for this or upcoming jobs please contact me in telegram @grayskripko

**Comment by grayskripko** [comment]
https://drive.google.com/file/d/1a7R9DmGyl9gh_SO6p3hBfDRY46NNkwrG/view?usp=sharing

**Comment by benjamin-meyer-ak** [comment]
Hi Sergey, thank you for getting in touch. I am all set on this particular project for now. Thank you for sending the demo. Hope that we can work together on some other project in the future!
